### ISSUE TITLE
Make sure search results page doesn't display Academy or College panel

### ISSUE THREAD

**Issue by narthur** [OuachitaHillsMinistries/oh-theme#3]
Example: https://ouachitahills.org/?s=address

**Comment by narthur** [comment]
https://codex.wordpress.org/Function_Reference/is_search

Put that in the functions.php function that determines page class.

**Comment by narthur** [comment]
Awaiting approval of pull request #22 which resolves this issue

**Comment by NathanielALiu** [comment]
Yeah! It's done!
